# Generalized regression neural network (GRNN) 
is a variation to radial basis neural networks. GRNN was suggested by D.F. Specht in 1991.

GRNN can be used for regression, prediction, and classification. GRNN can also be a good solution for online dynamical systems.

GRNN represents an improved technique in the neural networks based on the nonparametric regression. The idea is that every training sample will represent a mean to a radial basis neuron

## Dataset
We'll use Boston Housing Dataset.

In [1]:
import numpy as np
from sklearn import datasets, preprocessing
from sklearn.model_selection import train_test_split
from neupy import algorithms
import pandas as pd


In [2]:
d = pd.read_csv('CSM dataset.csv',sep=";")
dataset=  d.dropna()
dataset = dataset.iloc[:,1:]

In [3]:
dataset.head()

Year  Ratings  Genre        Gross       Budget  Screens  Sequel  \
0  2014.0      6.3    8.0       9130.0    4000000.0     45.0     1.0   
1  2014.0      7.1    1.0  192000000.0   50000000.0   3306.0     2.0   
2  2014.0      6.2    1.0   30700000.0   28000000.0   2872.0     1.0   
3  2014.0      6.3    1.0  106000000.0  110000000.0   3470.0     2.0   
4  2014.0      4.7    8.0   17300000.0    3500000.0   2310.0     2.0   

   Sentiment      Views    Likes  Dislikes  Comments  Aggregate Followers  
0        0.0  3280543.0   4632.0     425.0     636.0            1120000.0  
1        2.0   583289.0   3465.0      61.0     186.0           12350000.0  
2        0.0   304861.0    328.0      34.0      47.0             483000.0  
3        0.0   452917.0   2429.0     132.0     590.0             568000.0  
4        0.0  3145573.0  12163.0     610.0    1082.0            1923800.0

In [4]:
dataset.isnull().sum()

Year                   0
Ratings                0
Genre                  0
Gross                  0
Budget                 0
Screens                0
Sequel                 0
Sentiment              0
Views                  0
Likes                  0
Dislikes               0
Comments               0
Aggregate Followers    0
dtype: int64

In [5]:
dataset.head()

Year  Ratings  Genre        Gross       Budget  Screens  Sequel  \
0  2014.0      6.3    8.0       9130.0    4000000.0     45.0     1.0   
1  2014.0      7.1    1.0  192000000.0   50000000.0   3306.0     2.0   
2  2014.0      6.2    1.0   30700000.0   28000000.0   2872.0     1.0   
3  2014.0      6.3    1.0  106000000.0  110000000.0   3470.0     2.0   
4  2014.0      4.7    8.0   17300000.0    3500000.0   2310.0     2.0   

   Sentiment      Views    Likes  Dislikes  Comments  Aggregate Followers  
0        0.0  3280543.0   4632.0     425.0     636.0            1120000.0  
1        2.0   583289.0   3465.0      61.0     186.0           12350000.0  
2        0.0   304861.0    328.0      34.0      47.0             483000.0  
3        0.0   452917.0   2429.0     132.0     590.0             568000.0  
4        0.0  3145573.0  12163.0     610.0    1082.0            1923800.0

In [6]:
dataset['Ratings'].unique()

array([6.3, 7.1, 6.2, 4.7, 6.1, 6.5, 7.3, 5.7, 5.4, 5.2, 4.4, 6.6, 6.9,
       7.9, 8. , 7.8, 7.7, 4. , 6.8, 6.4, 5.8, 7.6, 5. , 8.2, 8.1, 5.6,
       8.7, 6. , 7. , 3.1, 4.8, 5.9, 7.2, 7.5, 5.5, 5.1, 7.4, 6.7, 4.2,
       4.9, 8.6, 8.3, 4.3, 4.6, 4.5])

In [7]:
X = dataset.iloc[:, :1].values
y = dataset.iloc[:, -1].values

In [8]:
scaler = preprocessing.StandardScaler()

# Split data into train partition and test partition
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.3)

## Define GRNN Model

In [9]:
grnn_model = algorithms.GRNN(std=0.1, verbose=True)


Main information

[ALGORITHM] GRNN

[OPTION] verbose = True
[OPTION] epoch_end_signal = None
[OPTION] show_epoch = 1
[OPTION] shuffle_data = False
[OPTION] step = 0.1
[OPTION] train_end_signal = None
[OPTION] std = 0.1



Train!

In [10]:
grnn_model.fit(X_train, y_train)

GRNN(verbose=True, step=None, show_epoch=None, shuffle_data=None, epoch_end_signal=None, train_end_signal=None, std=0.1)

Evaluate!

In [11]:
predictions = grnn_model.predict(X_test)
print(predictions)
print(y_test)

[[3594263.78723404]
 [3594263.78723404]
 [2601123.27777778]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [2601123.27777778]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [2601123.27777778]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [2601123.27777778]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [2601123.27777778]
 [2601123.27777778]
 [3594263.78723404]
 [3594263.78723404]
 [2601123.27777778]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [2601123.27777778]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [2601123.27777778]
 [2601123.27777778]
 [2601123.27777778]
 [3594263.78723404]
 [2601123.27777778]
 [3594263.78723404]
 [2601123.27777778]
 [2601123.27777778]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]
 [3594263.78723404]


In [12]:
y_test_predict = predictions.reshape(1, -1)[0]
y_test_predict

array([3594263.78723404, 3594263.78723404, 2601123.27777778,
       3594263.78723404, 3594263.78723404, 3594263.78723404,
       3594263.78723404, 3594263.78723404, 2601123.27777778,
       3594263.78723404, 3594263.78723404, 3594263.78723404,
       2601123.27777778, 3594263.78723404, 3594263.78723404,
       3594263.78723404, 3594263.78723404, 3594263.78723404,
       2601123.27777778, 3594263.78723404, 3594263.78723404,
       3594263.78723404, 3594263.78723404, 3594263.78723404,
       2601123.27777778, 2601123.27777778, 3594263.78723404,
       3594263.78723404, 2601123.27777778, 3594263.78723404,
       3594263.78723404, 3594263.78723404, 2601123.27777778,
       3594263.78723404, 3594263.78723404, 3594263.78723404,
       2601123.27777778, 2601123.27777778, 2601123.27777778,
       3594263.78723404, 2601123.27777778, 3594263.78723404,
       2601123.27777778, 2601123.27777778, 3594263.78723404,
       3594263.78723404, 3594263.78723404, 3594263.78723404,
       3594263.78723404,

In [13]:
y_test_predict[np.isnan(y_test_predict)] = 0

In [14]:
from sklearn.metrics import mean_squared_error


print(mean_squared_error(y_test, y_test_predict))

20064827855010.594
